version: "3.2"

services:
    ngml_reusable_component:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1818:8000
        volumes:
            # Re-use local composer cache via host-volume
            #- ~/.composer-docker/cache:/root/.composer/cache:delegated
            - .:/app
        networks:
            - ngml_reusable_component_network

    mysql:
        image: mariadb:10.5.8
        environment:
            - MYSQL_ROOT_PASSWORD=Ubuxa##99
            - MYSQL_DATABASE=forge
            - MYSQL_USER=forge
            - MYSQL_PASSWORD=Ubuxa##99
        networks:
            - ngml_reusable_component_network

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 1819:80
        environment:
            - PMA_HOST=mysql
            - PMA_PASSWORD=Ubuxa##99
        restart: unless-stopped
        volumes:
            # Re-use local composer cache via host-volume
            #- ~/.composer-docker/cache:/root/.composer/cache:delegated
            # Mount source-code for development
            - ./:/app
        networks:
            - ngml_reusable_component_network

networks:
    ngml_reusable_component_network:
        driver: bridge
